### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password"
}
### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}
### Pedal Index
GET http://localhost:3000/pedals.json
### Pedal Show
GET http://localhost:3000/pedal/2.json
### Loadout Index
GET http://localhost:3000/loadouts.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTc2MzgzNTV9.T9W3v3vnzXXjVop3jo6mUF4nHhyGbxb9onR3mL2Frzg 
### Loadout Show
GET http://localhost:3000/loadout/1.json
### Loadout Create
POST http://localhost:3000/loadouts.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTc1MDY1MTJ9.gdR3x4dI9S02N5TyPSAv5Zc2EfePYNDweYWN-YrBnX0

{
  "size": 3,
  "name": "Marcos cool loadout",
  "pedals": [
   1, 2, 3
  ]
}